### PR TITLE
extend the backbone by the children of the subtree not the root

### LINKED ISSUE #12: Missing node lengths on phylogenetic trees & node.name is returning values
The branch lengths are coming directly from FastTree output or being appended using skbio's append method in TreeNode.  When FastTree determines there is no length it gives it a value of "0.0" so I am not sure why there are lengths of "none".  Maybe this is the skbio TreeNode?  I'm not sure.

I checked a backbone tree with skbio (which is just 18S aligned sequences run on FastTree *without* any other modification or skbio methods) and it looks like it's outputting a length for some node.names when I traverse through the tree.  So I am not sure what's going.

I also ran the same script as below on a full ghost-tree .nwk and it looks like what it's doing is adding the "None" value to every insertion it makes into the backbone.  So possibly everywhere there is an insertion of a "mini" tree, there is a "None" value too.

I'll email some test files.

**I used this to check the backbone tree:**

from skbio import TreeNode

backbone_tree = TreeNode.read("nr_backbone_tree_gt.nwk", format="newick")

output = open("backbone_tree_analysis_file_032915.txt", "w")

for node in backbone_tree.traverse():
    output.write(str(node.name)+"\t"+str(node.length)+"\n")

output.close()

**Small output from analysis file (first column is node.name, 2nd is node.length):**

None	None
0.788	0.00128
0.806	0.00053
0.981	0.00055
AY665783.1.1694	0.00137
0.044	0.00055
AY657010.1.1771	0.00131
AF426952.1.1784	0.00618
0.737	0.00064
0.973	0.00054
0.968	0.00055
AY771602.1.1776	0.00066
0.492	0.00055
0.882	0.00132

### PR DESCRIPTION
**Pull request by ebolyen**
**DO NOT MERGE**
This will likely fix #12

@JTFouquier I am not sure how you would actually build the hybrid-tree, but I believe this is the issue. Maybe try this change out locally and see if it works?

### CODE REVIEW

**Comment by JTFouquier** [comment]
Hi Evan, I see what you mean, and have tried variations of TreeNode.extend and TreeNode.append but I cannot get it to extend the tree correctly. I pasted a tiny code showing the output as I would expect using ascii_art().  When changing it to extend the children, it causes an error (AttributeError: 'list' object has no attribute 'parent') or it truncates the second mini tree. I think this was why I originally stuck with the code below.  Let me know if you see anything obvious.  Thank you!

import skbio

from skbio import TreeNode
from six import StringIO

mini_tree1 = TreeNode.read(StringIO("((C4,C5),(C3,M4),(C1,(C2,M1)));"), format="newick")
mini_tree2 = TreeNode.read(StringIO("((a2,b2)c2,(d2,e2)f2);"), format="newick")

scaffold_tree = TreeNode.read(StringIO("(scaf1,scaf2);"), format="newick")

for node in scaffold_tree.traverse():
    if node.name == "scaf1":
        node.append(mini_tree1)
    if node.name == "scaf2":
        node.append(mini_tree2)

print scaffold_tree.ascii_art()

**Comment by ebolyen** [comment]
It looks like something seriously wrong is happening with extend. (Working up an issue right now for skbio) For now, let's just set the subtree root node length to 0. This should let you move forward...

**Comment by ebolyen** [comment]
Created an issue https://github.com/biocore/scikit-bio/issues/889 for this.

**Comment by ebolyen** [comment]
@JTFouquier I have updated this PR. It should work correctly now. What was happening was the list of children in the subtree was being mutated by the scaffold. So now I slice the entire thing to produce a copy.

**Comment by JTFouquier** [comment]
Thanks for your help!  I'll work on this soon.  Sorry it's a bug, but glad it was found!

**Pull request closed without merging**
