### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by jamespharper**
Professional English editing and clarifications

### CODE REVIEW

**Comment by JTFouquier** [comment]
@jamespharper thanks. I'll read this and pull later. For some reason it decreased coverage. Need to make sure all is okay.

**Comment by jamespharper** [comment]
@JTFouquier Yeah, I'm not sure why. Let me know if you need me to change anything.

**Comment by JTFouquier** [comment]
@jamespharper not sure why the "coverage" went down. Upon accepting the pull request, the coverage stayed at 70%. Only reason the coverage is not closer to 100% anyways is because *ghost-tree* relies on software that is not able to be installed on Travis, which checks the unit testing pass/fail rate and also the code coverage.  Thanks for the fixes!

**Comment by jamespharper** [comment]
Happy to help!

**Pull request merged**
