### PR TITLE
REL: make ghost-tree BSD licensed

### LINKED ISSUE #1: add license
Need license file at root of repo and in setup.py (in `setup` function call and PyPI classifiers).

### LINKED ISSUE #13: Click makes options wrap by single characters; options are difficult to read
Click works great, but it still wraps the command options by single characters.  Sometimes there are 4 to 5 options in ghost-tree, making reading options very difficult.  I’ve asked Click how the bug fix is going, and they have a workaround but haven't accepted it as a PR. Can ghost-tree be packaged with a modified version of Click (not released by Click)?

Click Issue:
https://github.com/mitsuhiko/click/issues/231  (they gave me directions on how to implement the PR, but I'm not sure it's worth trying due to future packaging of ghost-tree)
Click PR:
https://github.com/mitsuhiko/click/pull/240

According to @gregcaporaso via previous email (3/26/15):
"it's better to just leave as-is then try to build a modified version of click"

Example:

screen shot 2015-03-29 at 9 00 45 pm

### PR DESCRIPTION
**Pull request by jairideout**
Added 3-clause BSD license and updated author/maintainer/copyright to be
"ghost-tree development team".

Also fixed a link-rendering issue in README.rst. Removed unncessary licenses
for external tools. Made click 4.0 minimum required version.

Fixes #1. Fixes #13.

@gregcaporaso can you please review this to make sure the licensing-related stuff looks okay? Specifically the name of the author/maintainer/copyright holder ("ghost-tree development team").

### CODE REVIEW

**Comment by gregcaporaso** [comment]
This looks good to me, I don't have merge access to this repo though. 

Do we have the required external applications listed in the install docs? (Not necessary for this PR, but definitely for the first release.)

**Comment by jairideout** [comment]
Thanks for reviewing! There are no install docs yet. I agree we should include this info when they're added.

@JTFouquier can you please merge if you're good with these changes?

**Comment by jairideout** [comment]
Updated this PR to also fix #13 (click issue).

**Comment by jairideout** [comment]
Not sure why coverage/coveralls is saying coverage dropped, none of my changes should affect coverage. Looking at coveralls' report, it's not even marking any lines as having changed (as I'd expect). I think this is safe to merge.

**Pull request merged**
